/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StreakData = IDL.Record({
  'lastCheckInDate' : IDL.Int,
  'longestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'nickname' : IDL.Text,
  'joinDate' : IDL.Int,
  'level' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'nickname' : IDL.Text,
  'streakCount' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'userMessage' : IDL.Text,
  'timestamp' : IDL.Int,
  'coachResponse' : IDL.Text,
});
export const GameScore = IDL.Record({
  'date' : IDL.Int,
  'score' : IDL.Nat,
  'gameName' : IDL.Text,
});
export const Habit = IDL.Record({ 'name' : IDL.Text, 'completed' : IDL.Bool });
export const HabitsData = IDL.Record({
  'lastResetDate' : IDL.Int,
  'habits' : IDL.Vec(Habit),
});
export const ProgramProgress = IDL.Record({
  'completedDays' : IDL.Vec(IDL.Nat),
});
export const Badge = IDL.Record({ 'earnedDate' : IDL.Int, 'name' : IDL.Text });
export const XPData = IDL.Record({
  'totalXP' : IDL.Nat,
  'badges' : IDL.Vec(Badge),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addGameScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addLeaderboardEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addXP' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardBadge' : IDL.Func([IDL.Text], [], []),
  'clearAllUserData' : IDL.Func([], [], []),
  'clearLeaderboard' : IDL.Func([], [], []),
  'doCheckIn' : IDL.Func([], [StreakData], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getMyGameScores' : IDL.Func([], [IDL.Vec(GameScore)], ['query']),
  'getMyHabits' : IDL.Func([], [IDL.Opt(HabitsData)], ['query']),
  'getMyProgramProgress' : IDL.Func([], [IDL.Opt(ProgramProgress)], ['query']),
  'getMyStreak' : IDL.Func([], [IDL.Opt(StreakData)], ['query']),
  'getMyXP' : IDL.Func([], [IDL.Opt(XPData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markHabitComplete' : IDL.Func([IDL.Text], [], []),
  'markProgramDayComplete' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMyHabits' : IDL.Func([IDL.Vec(Habit)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StreakData = IDL.Record({
    'lastCheckInDate' : IDL.Int,
    'longestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'nickname' : IDL.Text,
    'joinDate' : IDL.Int,
    'level' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'nickname' : IDL.Text,
    'streakCount' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'userMessage' : IDL.Text,
    'timestamp' : IDL.Int,
    'coachResponse' : IDL.Text,
  });
  const GameScore = IDL.Record({
    'date' : IDL.Int,
    'score' : IDL.Nat,
    'gameName' : IDL.Text,
  });
  const Habit = IDL.Record({ 'name' : IDL.Text, 'completed' : IDL.Bool });
  const HabitsData = IDL.Record({
    'lastResetDate' : IDL.Int,
    'habits' : IDL.Vec(Habit),
  });
  const ProgramProgress = IDL.Record({ 'completedDays' : IDL.Vec(IDL.Nat) });
  const Badge = IDL.Record({ 'earnedDate' : IDL.Int, 'name' : IDL.Text });
  const XPData = IDL.Record({ 'totalXP' : IDL.Nat, 'badges' : IDL.Vec(Badge) });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addGameScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addLeaderboardEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addXP' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardBadge' : IDL.Func([IDL.Text], [], []),
    'clearAllUserData' : IDL.Func([], [], []),
    'clearLeaderboard' : IDL.Func([], [], []),
    'doCheckIn' : IDL.Func([], [StreakData], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getMyGameScores' : IDL.Func([], [IDL.Vec(GameScore)], ['query']),
    'getMyHabits' : IDL.Func([], [IDL.Opt(HabitsData)], ['query']),
    'getMyProgramProgress' : IDL.Func(
        [],
        [IDL.Opt(ProgramProgress)],
        ['query'],
      ),
    'getMyStreak' : IDL.Func([], [IDL.Opt(StreakData)], ['query']),
    'getMyXP' : IDL.Func([], [IDL.Opt(XPData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markHabitComplete' : IDL.Func([IDL.Text], [], []),
    'markProgramDayComplete' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMyHabits' : IDL.Func([IDL.Vec(Habit)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };