/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge { 'earnedDate' : bigint, 'name' : string }
export interface ChatMessage {
  'userMessage' : string,
  'timestamp' : bigint,
  'coachResponse' : string,
}
export interface GameScore {
  'date' : bigint,
  'score' : bigint,
  'gameName' : string,
}
export interface Habit { 'name' : string, 'completed' : boolean }
export interface HabitsData {
  'lastResetDate' : bigint,
  'habits' : Array<Habit>,
}
export interface LeaderboardEntry {
  'nickname' : string,
  'streakCount' : bigint,
}
export interface ProgramProgress { 'completedDays' : Array<bigint> }
export interface StreakData {
  'lastCheckInDate' : bigint,
  'longestStreak' : bigint,
  'currentStreak' : bigint,
}
export interface UserProfile {
  'nickname' : string,
  'joinDate' : bigint,
  'level' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface XPData { 'totalXP' : bigint, 'badges' : Array<Badge> }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<[string, string], undefined>,
  'addGameScore' : ActorMethod<[string, bigint], undefined>,
  'addLeaderboardEntry' : ActorMethod<[string, bigint], undefined>,
  'addXP' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardBadge' : ActorMethod<[string], undefined>,
  'clearAllUserData' : ActorMethod<[], undefined>,
  'clearLeaderboard' : ActorMethod<[], undefined>,
  'doCheckIn' : ActorMethod<[], StreakData>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getMyGameScores' : ActorMethod<[], Array<GameScore>>,
  'getMyHabits' : ActorMethod<[], [] | [HabitsData]>,
  'getMyProgramProgress' : ActorMethod<[], [] | [ProgramProgress]>,
  'getMyStreak' : ActorMethod<[], [] | [StreakData]>,
  'getMyXP' : ActorMethod<[], [] | [XPData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markHabitComplete' : ActorMethod<[string], undefined>,
  'markProgramDayComplete' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMyHabits' : ActorMethod<[Array<Habit>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];